### ISSUE TITLE
兄弟，加个使用说明呗

### ISSUE THREAD

**Issue by psc0606** [zlikun/python-crawler-douban-movie#1]
如题

**Comment by zlikun** [comment]
这个是我一篇博客的配套代码：[使用Python分析《我不是药神》豆瓣电影短评](https://my.oschina.net/zhanglikun/blog/1845888)

**Comment by zlikun** [comment]
哦，还少爬虫部分：[使用爬虫爬取豆瓣电影影评数据Python版](https://my.oschina.net/zhanglikun/blog/1845479)
